### ISSUE TITLE
Hostile AI Vessels will attack everything. Gunner AI and faction sides would be better.

### ISSUE THREAD

**Issue by Captain-Robertson** [Captain-Robertson/Stormworks---Bungeling-Raiders-Hostile-A.I.-#2]
As of the initial release only the "Captain" AI from the default AI script is used, a Microcontroller is used to search for other vehicles and train the weapons on them and another is used to assist in the aiming.
This means that there is no ability for them to identify between friend or foe, which essentially prevents the AI from ignoring each other and focusing on the player.

If we could somehow copy and paste the code from the Weapons DLC script (or even the script from the NPC Gunner mod on the workshop) into this one that adds the "Gunner" AI along with code that adds the Player, Neutral and Enemy as different sides, then this will go a huge way towards improving things.

**Comment by Captain-Robertson** [comment]
This is one of those enhancements that I'd love to have in this addon, but I'm under no illusions that this would require the most work to implement, as not only would we have to rip the Weapons DLC's Gunner AI code and put it into this one, but I'll also have to go back and rework all the ships I've created for this addon so that they can make use of said AI Gunners, as they will essentially be replacing the searching and designating part of the Fire Control Radar MC's I'm using (currently this takes up one whole MC and a radar).

Thankfully I'll only need two per ship, one for the forward arc and another for the rear arc - as AI gunners can only use robotic pivots (The Devs insist that velocity pivots with their 360 degree rotations just confuse them) which means they can't rotate more than 180 degrees left and right. 
Their job is just to aim their respective fire control radars at anything that's not in their faction and pull the trigger, the microcontrollers and their linked weaponry that I've already installed should hopefully be able to do the rest.

Again this enhancement is not vital, but would be the ultimate "Cherry on the top" for this addon, as it'll prevent the AI from shooting at their own factions ships and focus on the players instead.... Or at least that's the intention.

**Comment by Haiwei1027** [comment]
It does look challenging, but hopefully not too bad. Should we put the vehicle files on the repository as well for further work that involves modifying the vehicles. 
Perhaps we can find a shortcut by keeping current microcontrollers and in the addon we give the vehicle nearest (1-2?) ally's coordinate and feed that into the microcontroller to avoid ally.
So, that way we keep current AI ability(weapon DLC AI's aim are kind of bad) and minimal modification to the vehicles.

**Comment by Captain-Robertson** [comment]
That should be easy enough, I can put the vehicles as individually named xml files on Github for us to edit, rather than the whole folder - as the game likes to rename the vehicles files all the time when you replace them in the addon editor and at least this way it keeps it simple.

If you want to take a look at the MC's I've used to see if it is possible to use coordinates to prevent friendly fire then sure, it's definitely an option worth considering, especially if it can be made to work reliably.

I wouldn't worry about the AI's bad gunnery skills as they'll be using a modified version of 8PennieDeep's aimbot script - which is what I'm using already to excellent effect. All I need the AI to do is to point the fire control radar in the rough direction of their enemy and pull the trigger - I tested this out in the past using the AI Gunner addon and it worked spectacularly well when they're given the designator job role in the default drop down menu.

**Comment by Haiwei1027** [comment]
I see, I'll look into it tomorrow.

**Comment by Haiwei1027** [comment]
This feature's code is implemented now

**Comment by Captain-Robertson** [comment]
Currently in testing and looking very good indeed!

The only issue I've encountered so far is just an error that appears in the chat window that reads:
"hostile_ai   Failed to get transform on load"

This seems to appear whenever you hit something with a missile and it explodes (the missile that is, not the target), or if you click on the option to Cleanup a vehicle via the map, so I suspect it might possibly be related to the subgrids despawning?

**Comment by Captain-Robertson** [comment]
Will test this out again fully over the weekend but so far this looks like it works as intended and can be closed if no further bugs are found.

**Comment by Captain-Robertson** [comment]
The first iteration of the Gunner A.I. has been successful and this can now be closed... Next - IFF improvements.
