### ISSUE TITLE
Vehicles that are instantly destroyed sometimes reward the player twice

### ISSUE THREAD

**Issue by Captain-Robertson** [Captain-Robertson/Stormworks---Bungeling-Raiders-Hostile-A.I.-#3]
This mainly seems to be an issue with the smaller boats, especially if they're rather brutally deleted from existence by a Bertha cannon round or large anti-ship missile that's almost as big as the poor boat itself.

Maybe adding a check to prevent rewards being given out too soon after each other, or a more robust check for instantly despawned vehicles could be used?

**Comment by Haiwei1027** [comment]
I committed a push on Experimental that should be a more robust check for instantly despawned vehicles

**Comment by Captain-Robertson** [comment]
Brilliant! I'll test this out tonight as well.

**Comment by Captain-Robertson** [comment]
Works extremely well, getting no errors at all and all the rewards are being awarded correctly.

The only issue I've encountered during the couple of tests I ran is that when an enemy vehicle is instantly destroyed it's map marker is placed at X:0 Y:0 on the map (The beginner coastguard base) instead of being deleted. 

I encountered this bug before, back when I first implemented the map markers last week - mainly because of a careless typo when inserting the server.removeMapObject command in line 409, so I'm guessing the check to remove the map marker might have to be added earlier?

**Comment by Haiwei1027** [comment]
I'm not quite sure, since my code only been in the reward part I suspect that's a separate rare bug?

**Comment by Captain-Robertson** [comment]
Thoroughly tested before I retire for the night and I'm pleased to say that this one's been well and truly fixed also! :)

**Comment by Haiwei1027** [comment]
Nice!
