### ISSUE TITLE
Hostile A.I vessels should be able to respawn so that losses on the map are kept at around the same level

### ISSUE THREAD

**Issue by Captain-Robertson** [Captain-Robertson/Stormworks---Bungeling-Raiders-Hostile-A.I.-#4]
As it says in the description, a way of having a new AI vessel spawn somewhere on the map whenever one is despawned/destroyed would be an incredibly useful addition to the addon, as right now the number of AI vessels is finite, meaning that even though you can select 40 of them to spawn in at the beginning of a new career game that number will eventually drop down to 0 if enough of them are being destroyed fast enough.

This one isn't vital, just a quality of life improvement for those that want to focus on the combat aspect of the game and get frustrated when there's no more bad guys to fight against.

**Comment by Haiwei1027** [comment]
I've started work on this, will a style similar to how missions spawn in vanilla work? A timer that from time to time try to spawn a hostile with a minimum range and maximum range of the player. Until the vehicle limit is reached.

**Comment by Captain-Robertson** [comment]
That honestly sounds like the best approach and would be performance friendly too, as it's not checking every tick 'etc'.

I'm trying to get an idea of the best sort of ranges as we don't want them spawning too close or too far away, Probably between 10-40 km maybe? What are your thoughts?

**Comment by Haiwei1027** [comment]
10-40 seems good for now before we decides a different spawning pattern

**Comment by Captain-Robertson** [comment]
Nice one. I've updated the main branch with all the fixes last night, but once you're happy for this to be tested we'll add it to experimental.  It'll be interesting to see how this actually functions in game, especially as this is the first of the real enhancements.

**Comment by Haiwei1027** [comment]
I made a pull request for this feature. It works alright in my limited testing, I also made it spawn no enemy at the start for testing purposes you can add it back in easily by uncommenting the bit of code in onCreate()

**Comment by Captain-Robertson** [comment]
Good News!
Did some testing earlier varying the both the respawn times and maximum unit count and in all instances it works extremely well, with all losses being replaced within the exact time specified and all within 10-40Km.

I even uncommented out the code to begin a game with enemy units already in play and got the same results, all losses were replaced and it never went over the maximum amount the whole time I was testing it.

The only issue I ran into was when I first uncommented the code was that it didn't like the fact that it's missing the that first vehicle_count reference in line 1 and kept giving me a nil value error, but adding the line back in as a temporary fix seemed to work, even if it did make the options screen look a little untidy, what with it having two vehicle count sliders and all that.

I'll try testing it again later on once I've got some more spare time and see what happens, but so far it looks like it's working exactly as expected and I have yet to encounter any bugs, which is a very good sign.

**Comment by Haiwei1027** [comment]
In the latest version of Experimental I tackled the problem in the comment code by adding a start AI count property to decide how many AI should spawn at the start.

**Comment by Captain-Robertson** [comment]
Excellent! I'll make sure to use that instead when testing it out, thanks for the heads-up.

**Comment by Captain-Robertson** [comment]
I've been testing this out over the last couple of days and I'm pleased to say that this works exceptionally well, so it's probably safe to close this one off.
